name: Deploy LINE Rich Menu (Alias Switch A/B)

on:
  workflow_dispatch: {}          # 手動觸發
  push:                          # 可選：自動觸發
    branches: [main]
    paths:
      - 'richmenu/line/menuA.*'
      - 'richmenu/line/menuB.*'
      - 'richmenu/deploy_richmenu_alias.py'
      - 'requirements.txt'
      - '.github/workflows/deploy-richmenu-alias.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: richmenu-alias
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Deploy two-page rich menu (A/B)
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        run: |
          ls -al richmenu/line || true
          python richmenu/deploy_richmenu_alias.py \
            --imageA richmenu/line/menuA.png \
            --imageB richmenu/line/menuB.png \
            --set-default menu-a \
            --delete-others
